import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

/**
 * Flat config invoked through `eslint .` rather than `next lint`, which is
 * deprecated in Next 15 and prompts interactively when it cannot find a config —
 * that prompt is why the lint job hung the first time CI ran it.
 *
 * `FlatCompat` is needed because `eslint-config-next` is still published in the
 * eslintrc format.
 */
const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  {
    // next-env.d.ts is generated by Next on every build and intentionally uses a
    // triple-slash reference; there is nothing to fix in it.
    ignores: [
      '.next/**',
      'node_modules/**',
      'playwright-report/**',
      'test-results/**',
      'next-env.d.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      // The lazy modules use `require` deliberately, so that the baseline build
      // can drop the untaken branch. See components/lazy/README.md.
      '@typescript-eslint/no-require-imports': 'off',
      // Warn rather than error: an unused variable is worth flagging but is not a
      // reason to fail a build, and the `_`-prefix convention is intentional.
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // Test and script files run in Node and legitimately use console output.
    files: ['scripts/**/*.mjs', 'e2e/**/*.ts', '**/*.test.ts', '**/*.test.tsx'],
    rules: {
      'no-console': 'off',
    },
  },
];

export default config;
